### PR TITLE
fix: remove unnecessary Buffer.from usage

### LINKED ISSUE #147: `Buffer.from` usage cause KTX-parse and three.js includes polyfill whe used with `node-polyfill-webpack-plugin`
## Problem

While `Buffer.from` used in https://github.com/donmccurdy/KTX-Parse/blob/81959373fac956e88f0feaa2bb42dff4bc9542da/src/util.ts#L49-L62 will not be called if `TextEncoder` exists (which is true in  in modern environment), it does not work well when  [`node-polyfill-webpack-plugin`](https://github.com/Richienb/node-polyfill-webpack-plugin) is used in the same application.

`node-polyfill-webpack-plugin` will check and include the [`buffer`](https://www.npmjs.com/package/buffer) polyfill if any `Buffer` reference exists. In my setup I separated the polyfills as a different chunk to load dynamiclly if some Web API missing, but  in KTX-parse's case it's unintened and hard to work around.

The `buffer` package is ([8kb gziped](https://bundlephobia.com/package/buffer@6.0.3)) and modifies Uint8Array's prototype so better be avoided.

This behavior affects both `KTX-parse` and [the compiled version](https://github.com/mrdoob/three.js/blob/f5eaae8/examples/jsm/libs/ktx-parse.module.js) in Three.js.

## Possible fixes

As described in https://sindresorhus.com/blog/goodbye-nodejs-buffer avoid the `Buffer` global.

1. Both `TextDecoder` and `TextEncoder` are exposed as global in Node.js since [v11](https://nodejs.org/en/blog/release/v11.0.0#:~:text=TextEncoder%20and%20TextDecoder) (2018) so just delete the check.
3. Update the compiled version in Three.js

### PR DESCRIPTION
**Pull request by yue4u**
close #147

### CODE REVIEW

File: test/test.ts [hunk 1]
```diff
@@ -189,20 +188,8 @@ test('write::uastc', (t) => {
...
-	}) as any;
-
-	try {
-		const result = write(read(SAMPLE_UASTC));
-		t.true(result instanceof Uint8Array, 'success');
-	} finally {
-		Buffer.from = _from;
-	}
+	const result = write(read(SAMPLE_UASTC));
+	t.true(result instanceof Uint8Array, 'success');
```
Comment (yue4u) [inline test/test.ts:192]: Not sure if to delete this test since it not make much sense now.

**Comment by donmccurdy** [comment]
Thank you! Wasn't aware that TextEncoder/TextDecoder were globals in Node.js now. 🎊

File: test/test.ts (hunk 1 above)
Comment (donmccurdy) [reply test/test.ts:192]: I'll remove the test in a followup commit. 👍🏻
